---
- name: TOOLS | Install
  apt:
    name:
      - git
      - tree
      - htop
      - safe-rm
      - redis-server
      - unzip
      - apt-transport-https
      - lsb-release
      - ca-certificates
      - curl
      - wget
      - sudo
    state: present